[pytest]
filterwarnings =
    ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning:slowapi.extension
    ignore:.*httpx2.*:DeprecationWarning:starlette.testclient
    ignore:The 'timeout' parameter is deprecated.*:DeprecationWarning
    ignore:The 'verify' parameter is deprecated.*:DeprecationWarning